In [1]:
import numpy as np

In [2]:
x=[[1,3,4,],[5,6,7]]

In [3]:
arr1=np.array(x)

In [4]:
y=[[11,13,15],[26,28,29]]

In [5]:
arr2=np.array(y)

In [6]:
np.concatenate((arr1,arr2),axis=0) #rows wise

array([[ 1,  3,  4],
       [ 5,  6,  7],
       [11, 13, 15],
       [26, 28, 29]])

In [7]:
np.concatenate((arr1,arr2),axis=1) #column wise

array([[ 1,  3,  4, 11, 13, 15],
       [ 5,  6,  7, 26, 28, 29]])

In [9]:
np.vstack((arr1,arr2)) #in this method we no need axis

array([[ 1,  3,  4],
       [ 5,  6,  7],
       [11, 13, 15],
       [26, 28, 29]])

In [10]:
np.hstack((arr1,arr2))

array([[ 1,  3,  4, 11, 13, 15],
       [ 5,  6,  7, 26, 28, 29]])