In [1]:
import numpy as np

In [2]:
x=np.array([10,9,8,7,11])

In [3]:
np.sqrt(x) #its squire root function

array([3.16227766, 3.        , 2.82842712, 2.64575131, 3.31662479])

In [4]:
np.power(x,2) #its squire function

array([100,  81,  64,  49, 121], dtype=int32)

In [5]:
y=[7,6,5,4,6]

In [6]:
np.maximum(x,y)

array([10,  9,  8,  7, 11])