In [1]:
import numpy as np

In [2]:
x=np.array([1,3,4,5,6])

In [3]:
x[4]

6

In [4]:
x[x>3]

array([4, 5, 6])

In [5]:
x[[2,1]]

array([4, 3])

In [6]:
x=np.random.randn(10,10) #its slicing

In [7]:
x

array([[-0.87240366, -0.2679027 ,  0.76409309,  1.12462111, -0.38394264,
         1.44942471,  0.48313044, -0.95788102,  0.23733475, -0.35838673],
       [-0.68183772, -0.65179761,  0.26895292, -0.43397414, -1.08030935,
         0.06092873, -0.27359634,  0.73263924,  0.72877021,  0.18206405],
       [-1.21149579,  1.5569299 ,  1.40477619,  1.31268684,  0.55561665,
        -0.20880429,  1.38485038, -0.95165707, -0.53343626,  0.79507973],
       [-0.1471172 ,  0.02876385, -0.11424112, -0.79597779, -0.90857293,
        -0.02251045,  0.95230321,  0.09445112,  0.88727249,  0.60815124],
       [ 0.40536221, -1.49435392, -0.42062493, -2.53052474, -0.14339845,
         1.11910085, -0.85120194,  1.13523436,  0.18809846, -0.10978029],
       [-0.86336262,  1.46206793,  1.20180788,  1.03170104, -0.6296115 ,
        -0.28652432,  0.63693498, -0.73857145, -0.33864357,  0.1367863 ],
       [-1.7197391 ,  0.34016698, -0.14472711,  0.39560045,  1.14870393,
         1.26432137,  0.69397931,  0.89831495

In [8]:
x[0]

array([-0.87240366, -0.2679027 ,  0.76409309,  1.12462111, -0.38394264,
        1.44942471,  0.48313044, -0.95788102,  0.23733475, -0.35838673])

In [9]:
x[0][4]

-0.383942638488615

In [10]:
x[1:10:2]

array([[-0.68183772, -0.65179761,  0.26895292, -0.43397414, -1.08030935,
         0.06092873, -0.27359634,  0.73263924,  0.72877021,  0.18206405],
       [-0.1471172 ,  0.02876385, -0.11424112, -0.79597779, -0.90857293,
        -0.02251045,  0.95230321,  0.09445112,  0.88727249,  0.60815124],
       [-0.86336262,  1.46206793,  1.20180788,  1.03170104, -0.6296115 ,
        -0.28652432,  0.63693498, -0.73857145, -0.33864357,  0.1367863 ],
       [-0.4670397 ,  0.19231824,  1.06015725, -1.12641674,  1.13990917,
         0.44731043, -0.41529622,  0.42101514, -0.91919787, -2.00951105],
       [ 2.08185939,  1.00270776, -1.3449453 , -0.62828596,  0.36591719,
         0.41834522, -1.51285943,  0.57961981, -0.57765233, -0.84071809]])

In [12]:
x[::,0:4]

array([[-0.87240366, -0.2679027 ,  0.76409309,  1.12462111],
       [-0.68183772, -0.65179761,  0.26895292, -0.43397414],
       [-1.21149579,  1.5569299 ,  1.40477619,  1.31268684],
       [-0.1471172 ,  0.02876385, -0.11424112, -0.79597779],
       [ 0.40536221, -1.49435392, -0.42062493, -2.53052474],
       [-0.86336262,  1.46206793,  1.20180788,  1.03170104],
       [-1.7197391 ,  0.34016698, -0.14472711,  0.39560045],
       [-0.4670397 ,  0.19231824,  1.06015725, -1.12641674],
       [-1.32541768, -2.9816191 , -1.06402555, -0.01704324],
       [ 2.08185939,  1.00270776, -1.3449453 , -0.62828596]])

In [13]:
x=np.ones((5,5))

In [14]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
x[1:-1,1:-1]=0

In [16]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])