In [2]:
import numpy as np

In [3]:
x=np.zeros((4,4))

In [4]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.empty((6,6))

array([[6.82262004e-295,             nan, 3.82368604e-297,
        3.82368605e-297, 3.82368606e-297, 3.82368608e-297],
       [3.82368609e-297, 3.82368610e-297, 3.82368611e-297,
        2.50589094e-292, 2.88124434e-263, 1.07690240e-282],
       [8.11325540e-249, 1.46320209e-309, 2.01403582e-233,
        5.21840889e-296, 1.98808494e-263, 5.76407173e-220],
       [8.54209028e-254, 3.67023007e-244, 1.57696609e-234,
        6.77565611e-225, 2.91125529e-215, 1.90119468e-210],
       [2.42279450e-186, 3.40046560e-306, 4.20669745e-297,
        4.20585931e-172, 4.20669776e-297, 1.80640283e-162],
       [5.89824235e-249, 6.50368728e-172, 3.86331022e-244,
        2.77110245e-292, 5.08457200e-148, 2.68156159e+154]])

In [7]:
l=[1,2,3,4,5]

In [8]:
np.array(l)

array([1, 2, 3, 4, 5])

In [9]:
x=np.arange(1,100,10)

In [10]:
x.shape

(10,)

In [11]:
x=np.zeros((10,10))

In [12]:
x.shape

(10, 10)

In [13]:
y=x.reshape((2,2,5,5))

In [14]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [15]:
y.dtype

dtype('float64')

In [16]:
y.ndim

4

In [21]:
x=np.arange(1,10,2)

In [22]:
x

array([1, 3, 5, 7, 9])