In [1]:
import numpy as np

In [6]:
x=np.random.randn(4,5)

In [7]:
x

array([[ 0.49068513,  1.09779123, -0.87723986,  0.28527981, -0.71667556],
       [ 1.34348955, -1.55713664, -0.03660082,  1.67335169,  0.72719099],
       [ 1.00958938,  0.16718296, -0.84951903,  0.59640289, -2.11101036],
       [ 1.20508281, -0.63317264,  0.46163026, -1.32035012, -0.94610784]])

In [9]:
x.reshape((2,2,5))

array([[[ 0.49068513,  1.09779123, -0.87723986,  0.28527981,
         -0.71667556],
        [ 1.34348955, -1.55713664, -0.03660082,  1.67335169,
          0.72719099]],

       [[ 1.00958938,  0.16718296, -0.84951903,  0.59640289,
         -2.11101036],
        [ 1.20508281, -0.63317264,  0.46163026, -1.32035012,
         -0.94610784]]])

In [10]:
x.reshape((2,2,5),order="F")

array([[[ 0.49068513,  1.09779123, -0.87723986,  0.28527981,
         -0.71667556],
        [ 1.00958938,  0.16718296, -0.84951903,  0.59640289,
         -2.11101036]],

       [[ 1.34348955, -1.55713664, -0.03660082,  1.67335169,
          0.72719099],
        [ 1.20508281, -0.63317264,  0.46163026, -1.32035012,
         -0.94610784]]])

In [11]:
x.reshape((2,2,-1))

array([[[ 0.49068513,  1.09779123, -0.87723986,  0.28527981,
         -0.71667556],
        [ 1.34348955, -1.55713664, -0.03660082,  1.67335169,
          0.72719099]],

       [[ 1.00958938,  0.16718296, -0.84951903,  0.59640289,
         -2.11101036],
        [ 1.20508281, -0.63317264,  0.46163026, -1.32035012,
         -0.94610784]]])

In [12]:
x

array([[ 0.49068513,  1.09779123, -0.87723986,  0.28527981, -0.71667556],
       [ 1.34348955, -1.55713664, -0.03660082,  1.67335169,  0.72719099],
       [ 1.00958938,  0.16718296, -0.84951903,  0.59640289, -2.11101036],
       [ 1.20508281, -0.63317264,  0.46163026, -1.32035012, -0.94610784]])

In [15]:
x.ravel()

array([ 0.49068513,  1.09779123, -0.87723986,  0.28527981, -0.71667556,
        1.34348955, -1.55713664, -0.03660082,  1.67335169,  0.72719099,
        1.00958938,  0.16718296, -0.84951903,  0.59640289, -2.11101036,
        1.20508281, -0.63317264,  0.46163026, -1.32035012, -0.94610784])

In [16]:
x.flatten()

array([ 0.49068513,  1.09779123, -0.87723986,  0.28527981, -0.71667556,
        1.34348955, -1.55713664, -0.03660082,  1.67335169,  0.72719099,
        1.00958938,  0.16718296, -0.84951903,  0.59640289, -2.11101036,
        1.20508281, -0.63317264,  0.46163026, -1.32035012, -0.94610784])