In [1]:
import pandas as pd

In [2]:
obj=pd.Series([4, 7, -5, 3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64


# panda Series has two things in one objects
1 values
2 index

In [3]:
sales = pd.Series([100, 200, 100, 400])
print(sales.values)
print(sales.index)

[100 200 100 400]
RangeIndex(start=0, stop=4, step=1)


In [4]:
sales = pd.Series([100, 200, 100, 400], index= ['Jan', 'Feb', 'Mar', 'Apr' ])
print(sales)
print(sales.values)
print(sales.index)

Jan    100
Feb    200
Mar    100
Apr    400
dtype: int64
[100 200 100 400]
Index(['Jan', 'Feb', 'Mar', 'Apr'], dtype='object')


In [5]:
sales = pd.Series([100, 200, 100, 400], index= ['Jan', 'Feb', 'Mar', 'Apr' ], name= "4 Month sales")
print(sales)

Jan    100
Feb    200
Mar    100
Apr    400
Name: 4 Month sales, dtype: int64


# create a pandas series to store a canteen data to hold values of how many sandwitches sold each day (one week)

In [6]:
sw = pd.Series([20, 30, 20, 25, 40, 15, 0], index = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'])
print(sw)

mon    20
tue    30
wed    20
thu    25
fri    40
sat    15
sun     0
dtype: int64


In [7]:
print(sw[1])
print(sw['tue'])
print(sw['sun'])

30
30
0


In [8]:
print(sw[[3,5]])
print(sw[['thu', 'sat']])

thu    25
sat    15
dtype: int64
thu    25
sat    15
dtype: int64


In [9]:
print(sw[sw > 20])

tue    30
thu    25
fri    40
dtype: int64


In [10]:
print(sw)

mon    20
tue    30
wed    20
thu    25
fri    40
sat    15
sun     0
dtype: int64


In [11]:
sw = sw /2
print(sw)

mon    10.0
tue    15.0
wed    10.0
thu    12.5
fri    20.0
sat     7.5
sun     0.0
dtype: float64


In [12]:
sw = sw /2
print(sw)

mon     5.00
tue     7.50
wed     5.00
thu     6.25
fri    10.00
sat     3.75
sun     0.00
dtype: float64


In [13]:
print(sw)

mon     5.00
tue     7.50
wed     5.00
thu     6.25
fri    10.00
sat     3.75
sun     0.00
dtype: float64


In [14]:
'mon' in sw

True

In [15]:
1 in sw

False

In [16]:
import numpy as np
ar = np.array([2, 4, 5, 6, 7,])
ind = np.array(['a', 'b', 'c', 'd', 'e'])

obj2 = pd.Series(ar, index = ind)                 #in this method we can convert numpy data into pandas
print(obj2)

a    2
b    4
c    5
d    6
e    7
dtype: int32


In [17]:
sdata = {"Sindh": 35000, "Punjab": 45000, "KPK": 25000, "Balochistan": 20000}
tax_by_state = pd.Series(sdata, index = ["Punjab", "Sindh", "KPK", "Balochistan", "GB"])
print(tax_by_state)

Punjab         45000.0
Sindh          35000.0
KPK            25000.0
Balochistan    20000.0
GB                 NaN
dtype: float64


**Source for series data**
* Direct data in the series method
* From numpy array or list
* From dictionary

# Data Frame Prectice

In [18]:
apples = pd.Series([4,2,3,4], index = ["mon", "tue", "wed", "thu"])
oranges = pd.Series([1,2,3,4], index = ["mon", "tue", "wed", "thu"])

#print(apples, oranges)
data = {"apples": apples, "oranges": oranges}
fruits = pd.DataFrame(data)
print(fruits)



     apples  oranges
mon       4        1
tue       2        2
wed       3        3
thu       4        4


In [19]:
state= ['Sindh', 'Punjab', 'Balochistan', 'KPK', 'Gilgit', 'Kashmir']
data= {'state': state,
       'year' : [2001, 2001, 2002, 2003, 2004, 2005],
       'city' : [200, 300, 105, 100, 103, 220]}
       
frame = pd.DataFrame(data, index = ['1st', '2nd', '3rd', '4th', '5th', '6th'])
print(frame)

           state  year  city
1st        Sindh  2001   200
2nd       Punjab  2001   300
3rd  Balochistan  2002   105
4th          KPK  2003   100
5th       Gilgit  2004   103
6th      Kashmir  2005   220


In [20]:
frame.head()
pd.DataFrame(data, columns=['year', 'state', 'city']) # we can change the name of the column

year        state  city
0  2001        Sindh   200
1  2001       Punjab   300
2  2002  Balochistan   105
3  2003          KPK   100
4  2004       Gilgit   103
5  2005      Kashmir   220

In [21]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'city', 'pop'], #we can create more columns in this method but it will nan untill we putt the values 
        index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2.head()

year        state  city  pop
one    2001        Sindh   200  NaN
two    2001       Punjab   300  NaN
three  2002  Balochistan   105  NaN
four   2003          KPK   100  NaN
five   2004       Gilgit   103  NaN

In [22]:
print(frame2.columns)
print(frame2.index)

Index(['year', 'state', 'city', 'pop'], dtype='object')
Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')


# A column in a DataFrame can be retrieved as a Series ethier by dic-like notation or by attribute:

In [23]:
data['state'] #dic-like notation to acceses data

['Sindh', 'Punjab', 'Balochistan', 'KPK', 'Gilgit', 'Kashmir']

In [24]:
frame2["year"]

one      2001
two      2001
three    2002
four     2003
five     2004
six      2005
Name: year, dtype: int64

In [25]:
frame["state"]

1st          Sindh
2nd         Punjab
3rd    Balochistan
4th            KPK
5th         Gilgit
6th        Kashmir
Name: state, dtype: object

In [26]:
#there is another method attribute style for accesing dataframe in this we use frame2.state
frame2.city

one      200
two      300
three    105
four     100
five     103
six      220
Name: city, dtype: int64

In [27]:
print(frame2.loc['one']) # in this method we can access index wise columns 
frame.head()
frame.head() #its means it will access last input otherwise print function must access if we want multiple ouputs we use print

year      2001
state    Sindh
city       200
pop        NaN
Name: one, dtype: object


state  year  city
1st        Sindh  2001   200
2nd       Punjab  2001   300
3rd  Balochistan  2002   105
4th          KPK  2003   100
5th       Gilgit  2004   103

# colmns can be modified by assignmnet, for exp empty 'pop' column could be assigned a scalar value or an array of values

In [28]:
frame2['pop'] = 5.5
frame2.head()

year        state  city  pop
one    2001        Sindh   200  5.5
two    2001       Punjab   300  5.5
three  2002  Balochistan   105  5.5
four   2003          KPK   100  5.5
five   2004       Gilgit   103  5.5

In [29]:
ln = (len(frame2)) #finding num of rows in dataframe
#print(frame2)
rng = np.arange(ln)
print(rng)
frame2['pop'] = rng
frame2

[0 1 2 3 4 5]


year        state  city  pop
one    2001        Sindh   200    0
two    2001       Punjab   300    1
three  2002  Balochistan   105    2
four   2003          KPK   100    3
five   2004       Gilgit   103    4
six    2005      Kashmir   220    5

In [30]:
val = pd.Series([1.2, 1.4, 1.6, 2.3, 2.2, 2.4],
         index = ['one', 'two', 'three', 'four', 'five', 'six']) #index must
frame2['pop'] = val
frame2

year        state  city  pop
one    2001        Sindh   200  1.2
two    2001       Punjab   300  1.4
three  2002  Balochistan   105  1.6
four   2003          KPK   100  2.3
five   2004       Gilgit   103  2.2
six    2005      Kashmir   220  2.4

# Function Application and Mapping

In [31]:
fr = fr = pd.DataFrame(np.random.randn(4, 3),
                       columns=list('bde'),
                       index=['khi', 'hyd', 'lhr', 'skr'])

print(fr)
#print(np.abs(fr)) #its return to absulate value of number negetive values become posetive
#print(fr['d']. min())
#print(fr['d']. max())
#print(fr['d']. max() - fr['d']. min())

f = lambda x: x.max() - x.min()
df = fr.apply(f)
print(df, type(df))
df = fr.apply(f, axis=1)
print(df)

def min_max(x):
    minimum = x.min()
    maximum = x.max()
    return pd.Series([maximum, minimum], index = ['min', 'max'])

df = fr.apply(min_max)
print(df, type(df))

            b         d         e
khi  0.628606  1.048542  1.104674
hyd  0.574788 -0.359803  0.186367
lhr -0.484583 -0.945272 -1.078382
skr  1.137369  0.222998  0.380801
b    1.621951
d    1.993814
e    2.183056
dtype: float64 <class 'pandas.core.series.Series'>
khi    0.476068
hyd    0.934590
lhr    0.593799
skr    0.914371
dtype: float64
            b         d         e
min  1.137369  1.048542  1.104674
max -0.484583 -0.945272 -1.078382 <class 'pandas.core.frame.DataFrame'>


# Arithimetic and Data Alignment

In [32]:
n = np.arange(9) #arange means count numbers
print(n)
n.reshape(3, 3) #reshape means its convert to rows and culumns

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
df1 = pd.DataFrame(np.arange (9.).reshape (3, 3),
                   columns=list('bcd'),
                   index=['sindh', 'punjab', 'balochistan' ])
        
df2 = pd.DataFrame(np.arange(12.).reshape(4, 3),
                   columns=list('bde'),
                   index=['sindh', 'balochistan', 'kpk', 'gilgit'])

print(df1)
print(df2) #applying plus operation between two df

df3 = df1 + df2
print(df3)
#index and columns must match otherwise values will be nan
                   

               b    c    d
sindh        0.0  1.0  2.0
punjab       3.0  4.0  5.0
balochistan  6.0  7.0  8.0
               b     d     e
sindh        0.0   1.0   2.0
balochistan  3.0   4.0   5.0
kpk          6.0   7.0   8.0
gilgit       9.0  10.0  11.0
               b   c     d   e
balochistan  9.0 NaN  12.0 NaN
gilgit       NaN NaN   NaN NaN
kpk          NaN NaN   NaN NaN
punjab       NaN NaN   NaN NaN
sindh        0.0 NaN   3.0 NaN


# Arithimetic Method with Fill Values

In [34]:
df3 = pd.DataFrame(np.arange(12.).reshape(3, 4),
                   columns=list('abcd'))
df4 = pd.DataFrame(np.arange(20.).reshape(4, 5),
                   columns=list('abcde'))

print(df3)
print(df4)
df5 = df3 + df4
print()
print("direct + value without fill_values")
print(df5)
print('........')
print()
# We can use add method for filling NaN cells with a value
# Nan will be replaced by 1 and then addition operation will apply

print("addition using a method with replacing Nan with 1")
df5 = df3.add(df4, fill_value=1)
print(df5)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

direct + value without fill_values
      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN
........

addition using a method with replacing Nan with 1
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   5.0
1   9.0  11.0  13.0  15.0  10.0
2  18.0  20.0  22.0  24.0  15.0
3  16.0  17.0  18.0  19.0  20.0


# Operation Between DataFrame and Series

In [35]:
fr = pd.DataFrame(np.arange(12.).reshape(4, 3),
                  columns=list('bde'),
                  index=['Asif','Ali','Amjad','Yameen'])
series = fr.iloc[0]
print(fr)
#print(series)
#print(series.values)
#print(series.index)
#print(fr - series)
# step 1 run above cammand after uncomment
# step 2 comment above prints cammand except fr
print('using new series')
series = pd.Series([1,2,3], index=list('bde'))
print(series.index, series.values)
print(fr - series)
# dataframe columns name wil be match with series index
# because its rows wise operation

          b     d     e
Asif    0.0   1.0   2.0
Ali     3.0   4.0   5.0
Amjad   6.0   7.0   8.0
Yameen  9.0  10.0  11.0
using new series
Index(['b', 'd', 'e'], dtype='object') [1 2 3]
          b    d    e
Asif   -1.0 -1.0 -1.0
Ali     2.0  2.0  2.0
Amjad   5.0  5.0  5.0
Yameen  8.0  8.0  8.0


# Deleting data (rows and columns from DataFrame)

In [36]:
data_df = pd.DataFrame(np.arange(16).reshape(4,4),
                       index= ['Asif', 'Amjad', 'Ali', 'Younis'],
                       columns=['one', 'two', 'three', 'four'])

print(data_df)


        one  two  three  four
Asif      0    1      2     3
Amjad     4    5      6     7
Ali       8    9     10    11
Younis   12   13     14    15


In [37]:
data_df = pd.DataFrame(np.arange(16).reshape(4,4),
                       index= ['Asif', 'Amjad', 'Ali', 'Younis'],
                       columns=['one', 'two', 'three', 'four'])

print(data_df, "\n")

# we can drop/delete values by passing axis=1 and axis=0
# axis=1 means columns wise and axis=0 rows wise

data_df = data_df.drop('three', axis=1) #in this method values deleted by column wise
print(data_df)
data_df = data_df.drop('Younis', axis=0) #in this method values deleted by rows wise
print(data_df)

        one  two  three  four
Asif      0    1      2     3
Amjad     4    5      6     7
Ali       8    9     10    11
Younis   12   13     14    15 

        one  two  four
Asif      0    1     3
Amjad     4    5     7
Ali       8    9    11
Younis   12   13    15
       one  two  four
Asif     0    1     3
Amjad    4    5     7
Ali      8    9    11


# Sorting and Ranking

In [38]:
f = pd.DataFrame(np.arange(8).reshape(2,4),
                 index=['three', 'one'],
                 columns=['d', 'a', 'b', 'c'])

print(f)
print()
print(f.sort_index())
print()
print(f.sort_index(axis=1, ascending=True))

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

       a  b  c  d
three  1  2  3  0
one    5  6  7  4


# Summrizing and Computing Descriptive Statistics

In [39]:
dff = pd.DataFrame([[4,np.nan], [8.2, -5.5],
                   [np.nan, np.nan], [1.4, -6.7]],
                   index=['a', 'b', 'c', 'd'], columns=['one', 'two'])

print(dff)
print()
print(dff.sum())
print()
print(dff.sum(axis='columns'))# rows wise

   one  two
a  4.0  NaN
b  8.2 -5.5
c  NaN  NaN
d  1.4 -6.7

one    13.6
two   -12.2
dtype: float64

a    4.0
b    2.7
c    0.0
d   -5.3
dtype: float64


In [40]:
print(dff)
n = dff.mean(axis='columns') #its divide with 1, 
print()
print(n)

   one  two
a  4.0  NaN
b  8.2 -5.5
c  NaN  NaN
d  1.4 -6.7

a    4.00
b    1.35
c     NaN
d   -2.65
dtype: float64


In [41]:
print(dff)
n = dff.mean(axis='columns', skipna=False) #its divide with 0
print()
print(n)

   one  two
a  4.0  NaN
b  8.2 -5.5
c  NaN  NaN
d  1.4 -6.7

a     NaN
b    1.35
c     NaN
d   -2.65
dtype: float64


# Unique Values

In [42]:
d = pd.DataFrame([
                  [1.4, 1.7, 1.4, np.nan], [7.1, -4.5, np.nan, 1.5], 
                  [1.3,2.4,np.nan,4.5], [3.4, 5.5, 6.5, 3.3]
               ], index=['a', 'b', 'c','d'], columns=['one', 'two', 'three', 'four'])

print(d)
print()
print(d['one'].unique), (d['three'].unique)
d['three'].value_counts()

   one  two  three  four
a  1.4  1.7    1.4   NaN
b  7.1 -4.5    NaN   1.5
c  1.3  2.4    NaN   4.5
d  3.4  5.5    6.5   3.3

<bound method Series.unique of a    1.4
b    7.1
c    1.3
d    3.4
Name: one, dtype: float64>


1.4    1
6.5    1
Name: three, dtype: int64

# How to Reindex and use of ffill method

In [43]:
obj0 = pd.Series(['blue', 'green', 'yellow'], index= [0, 3, 6])

print(obj0)
print()
obj = obj0.reindex(range(9))
print(obj)
print()
objj = obj0.reindex(range(9), method='ffill')
print(objj)

0      blue
3     green
6    yellow
dtype: object

0      blue
1       NaN
2       NaN
3     green
4       NaN
5       NaN
6    yellow
7       NaN
8       NaN
dtype: object

0      blue
1      blue
2      blue
3     green
4     green
5     green
6    yellow
7    yellow
8    yellow
dtype: object


In [44]:
states = pd.DataFrame(np.arange(9).reshape(3,3),
                     index=['a', 'b', 'c',], columns= ['Sindh', 'Punjab', 'Balochistan'])

print(states)
print()
st = states.reindex(['a', 'b', 'c', 'd']) #without perameter method
print(st)
print()
stt = states.reindex(['a', 'b', 'c', 'd'], method='ffill' ) #with perameter method ffill
print(stt)

   Sindh  Punjab  Balochistan
a      0       1            2
b      3       4            5
c      6       7            8

   Sindh  Punjab  Balochistan
a    0.0     1.0          2.0
b    3.0     4.0          5.0
c    6.0     7.0          8.0
d    NaN     NaN          NaN

   Sindh  Punjab  Balochistan
a      0       1            2
b      3       4            5
c      6       7            8
d      6       7            8


# Column name changig with reindex method

In [45]:
states = pd.DataFrame(np.arange(9).reshape(3,3),
                     index=['a', 'b', 'c',], columns= ['Sindh', 'Punjab', 'Balochistan'])

print(states)
print()
states_name= ['Sindh', 'Punjab', 'Balochistan', 'KPK']

s = states.reindex(columns=states_name, method='ffill') # if we did not use method ffill value was show nan
print(s)

   Sindh  Punjab  Balochistan
a      0       1            2
b      3       4            5
c      6       7            8

   Sindh  Punjab  Balochistan  KPK
a      0       1            2    1
b      3       4            5    4
c      6       7            8    7


# Indexing selection and filtering

In [46]:
data_df = pd.DataFrame(np.arange(16).reshape(4,4),
                       index= ['Asif', 'Amjad', 'Ali', 'Younis'],
                       columns=['one', 'two', 'three', 'four'])

#print(data_df, "\n")
#df2 = (data_df[ ['one', 'three'] ]) # its selection
#print(df2)
#print(data_df[2:]) #same like numpy only two rows print, fillter
#print(data_df['one']) #its dictionary like style only one column values are print
#print(data_df.one) #its attribute style 
#print(data_df.one[2:]) #filter on both rows and columns

#conditional selection
print(data_df[data_df['three'] > 5]) # in this method three columns values is grater than 5
print()
print(data_df.three[data_df['three'] > 5]) #if we want particular column


        one  two  three  four
Amjad     4    5      6     7
Ali       8    9     10    11
Younis   12   13     14    15

Amjad      6
Ali       10
Younis    14
Name: three, dtype: int32


In [47]:
data_df = pd.DataFrame(np.arange(16).reshape(4,4),
                       index= ['Asif', 'Amjad', 'Ali', 'Younis'],
                       columns=['one', 'two', 'three', 'four'])

print(data_df, "\n")
#in the loc method specify row label
#then specify columns name
# remember multiple columns names require array notation
#print(data_df.loc[['Amjad'], ['two', 'three']])
#print(data_df.loc['Amjad']) # without specify columns names

print(data_df.iloc[2:, [3, 0, 1]]) #using number instead of labels
print(data_df.iloc[:])


        one  two  three  four
Asif      0    1      2     3
Amjad     4    5      6     7
Ali       8    9     10    11
Younis   12   13     14    15 

        four  one  two
Ali       11    8    9
Younis    15   12   13
        one  two  three  four
Asif      0    1      2     3
Amjad     4    5      6     7
Ali       8    9     10    11
Younis   12   13     14    15
