In [1]:
import numpy as np

In [2]:
a=np.random.randn((10))

In [3]:
b=np.random.randn((10))

In [4]:
a

array([-0.68804746,  0.00512249,  1.44873833, -0.70424554,  1.53900312,
       -0.74299609,  0.86701726,  1.29485371, -1.33250155, -1.7158209 ])

In [5]:
b

array([ 0.78133002, -0.45694733, -1.11480562,  1.57043539, -0.47520613,
       -0.56485134,  1.79623236,  0.33018352,  1.14250963, -0.26504171])

In [6]:
a+b

array([ 0.09328256, -0.45182484,  0.33393271,  0.86618985,  1.06379699,
       -1.30784743,  2.66324963,  1.62503723, -0.18999192, -1.98086261])

In [7]:
a-b

array([-1.46937748,  0.46206982,  2.56354396, -2.27468094,  2.01420925,
       -0.17814475, -0.9292151 ,  0.9646702 , -2.47501118, -1.45077919])

In [8]:
2*a

array([-1.37609492,  0.01024498,  2.89747666, -1.40849109,  3.07800624,
       -1.48599218,  1.73403453,  2.58970743, -2.6650031 , -3.4316418 ])

In [9]:
3/a

array([ -4.36016434, 585.65250723,   2.07076732,  -4.25987786,
         1.94931379,  -4.03770631,   3.46013871,   2.31686404,
        -2.25140451,  -1.74843423])

In [10]:
a>0

array([False,  True,  True, False,  True, False,  True,  True, False,
       False])

In [11]:
a[a>0]

array([0.00512249, 1.44873833, 1.53900312, 0.86701726, 1.29485371])